version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: softwarehouse-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - softwarehouse-network

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: softwarehouse-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - softwarehouse-network

  # DB
  db:
    image: postgres:13-alpine
    container_name: softwarehouse-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
    networks:
      - softwarehouse-network

networks:
  softwarehouse-network:
    driver: bridge